with-expecter: true
testonly: True
all: true
dir: "test/mocks/{{.PackagePath}}"
filename: "mock_{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}_mocks"
recursive: true
packages:
  github.com/optiswift/cinnamon:

